# Generated by Django 5.2.7 on 2025-10-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('Teacher', 'Teacher'), ('Office Staff', 'Office Staff')], default='Teacher', max_length=20)),
                ('designation', models.CharField(blank=True, choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Office staff', 'Office staff'), ('Other', 'Other')], max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('identification_document', models.FileField(blank=True, null=True, upload_to='staff/id_docs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('educational_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(default=1)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_year', models.PositiveIntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_number', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bachelor_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('identification_document', models.FileField(blank=True, null=True, upload_to='students/id_docs/')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
