# Generated by Django 5.2.7 on 2025-10-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_staff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
