# Generated by Django 5.2.7 on 2025-10-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_years', models.PositiveIntegerField(default=0)),
                ('num_semesters', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('semester', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('LAB', 'Lab'), ('PROJECT', 'Project'), ('VIVA', 'Comprehensive Viva'), ('SEMINAR', 'Seminar'), ('AEC', 'AEC'), ('MDC', 'MDC'), ('DSC', 'DSC'), ('BRIDGE', 'Bridge Course')], max_length=20)),
                ('credits', models.PositiveIntegerField()),
                ('lecture_hours', models.PositiveIntegerField(default=0)),
                ('practical_hours', models.PositiveIntegerField(default=0)),
                ('integrated_lab', models.BooleanField(default=False)),
                ('internal_marks', models.PositiveIntegerField(default=0)),
                ('external_marks', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('is_project', models.BooleanField(default=False)),
                ('is_viva', models.BooleanField(default=False)),
            ],
        ),
    ]
