# Generated by Django 5.2.7 on 2025-10-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_address_and_more'),
        ('program_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_hod': True, 'role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to='accounts.userprofile'),
        ),
    ]
