# Generated by Django 5.2.7 on 2025-10-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0003_alter_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tutorial_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
