# Generated by Django 5.2.7 on 2025-10-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('program_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.ForeignKey(blank=True, help_text='If the user is HOD/teacher, link to their Program', null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.program'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
