# Generated by Django 5.2.7 on 2025-10-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('program_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='educational_qualification',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student_email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.program'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('OfficeStaff', 'Office Staff'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
