# Generated by Django 5.2.7 on 2025-10-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
