# Generated by Django 5.2.7 on 2025-10-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_facultyassignment_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
