# Generated by Django 5.2.7 on 2025-11-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_semester',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
