# Generated by Django 5.2.7 on 2025-10-30 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program_management', '0005_alter_facultyassignment_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('SERIES', 'Series Exam'), ('MODEL', 'Model Exam'), ('UNIVERSITY', 'University Exam')], max_length=20)),
                ('file', models.FileField(upload_to='question_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_management.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_management.subject')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'userprofile__role__in': ['Teacher', 'HOD']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('QUESTION_PAPER', 'Question Paper'), ('TIMETABLE', 'Time Table')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program_management.program')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('exam_type', models.CharField(choices=[('SERIES', 'Series Exam'), ('MODEL', 'Model Exam'), ('UNIVERSITY', 'University Exam')], max_length=20)),
                ('file', models.FileField(upload_to='timetables/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_management.program')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'userprofile__role': 'OfficeStaff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
