# Generated by Django 5.2.7 on 2025-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='resourcenotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='title',
            field=models.CharField(default='Untitled Question Paper', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='title',
            field=models.CharField(default='Untitled Timetable', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='file',
            field=models.FileField(upload_to='resources/question_papers/'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='file',
            field=models.FileField(upload_to='resources/timetables/'),
        ),
    ]
