# Generated by Django 5.2.7 on 2025-11-01 08:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program_management', '0005_alter_facultyassignment_teacher'),
        ('user_management', '0004_alter_staff_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_semester', models.PositiveIntegerField()),
                ('admission_year', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('REG', 'Regular'), ('IMP', 'Improvement'), ('SUP', 'Supplementary')], default='REG', max_length=3)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=8, null=True)),
                ('pass_fail', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_external_semester_results', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_semester_results', to='user_management.student')),
            ],
            options={
                'ordering': ['student', 'exam_semester'],
                'indexes': [models.Index(fields=['program', 'exam_semester', 'admission_year'], name='marks_manag_program_63e3f9_idx')],
                'unique_together': {('student', 'exam_semester', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='ExternalSubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_semester', models.PositiveIntegerField()),
                ('admission_year', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('REG', 'Regular'), ('IMP', 'Improvement'), ('SUP', 'Supplementary')], default='REG', max_length=3)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(blank=True, max_length=8, null=True)),
                ('pass_fail', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_external_marks', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_management.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_subject_marks', to='user_management.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_subject_marks', to='program_management.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'indexes': [models.Index(fields=['program', 'exam_semester', 'admission_year'], name='marks_manag_program_958f58_idx')],
                'unique_together': {('student', 'subject', 'exam_semester', 'exam_type')},
            },
        ),
    ]
