# Generated by Django 5.2.7 on 2025-11-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsubjectmark',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
